//! Bounded local MCP transport, versioned wire DTOs, capability negotiation,
//! and protocol-error mapping over RepoWitness application use cases.
//!
//! This package deliberately has no Git, filesystem, or SQLite dependency.
//! The CLI composition root injects those concrete operations through
//! [`RepositoryService`].

mod server;
mod transport;
mod wire;

pub use server::{
    DEFAULT_MCP_OPERATION_CONCURRENCY, MAX_MCP_REGISTERED_REPOSITORIES, McpRepositoryRegistryError,
    McpServeError, McpToolSurface, RepoWitnessMcpServer, serve_stdio,
    serve_stdio_with_memory_writes, serve_stdio_with_repository_catalog,
    serve_stdio_with_repository_registry, serve_stdio_with_surface,
    serve_stdio_with_surface_and_native_tasks, serve_stdio_with_surface_tasks_and_personal_memory,
};
pub use transport::{BoundedLineReader, BoundedLineReaderLimitError, MAX_MCP_INPUT_LINE_BYTES};
pub use wire::{
    ARCHITECTURE_MAP_TOOL_NAME, ARCHITECTURE_OVERVIEW_LIMITATIONS, ARCHITECTURE_OVERVIEW_TOOL_NAME,
    ArchitectureMapInput, ArchitectureMapOutput, ArchitectureMapServiceRequest,
    ArchitectureOverviewInput, ArchitectureOverviewOutput, ArchitectureOverviewServiceRequest,
    CODE_GRAPH_QUERY_PROFILE_VERSION, CODE_GRAPH_QUERY_SCHEMA_VERSION, CODE_GRAPH_QUERY_TOOL_NAME,
    CODE_SEARCH_TOOL_NAME, COMPATIBILITY_PROFILE_VERSION, CONTEXT_BUILD_TOOL_NAME,
    CodeGraphQueryInput, CodeGraphQueryOutput, CodeGraphQueryResultOutput,
    CodeGraphQueryServiceRequest, CodeSearchInput, CodeSearchOutput, CodeSearchServiceRequest,
    CompatibilityGraphSchema, CompatibilityGraphSchemaLimits, CompatibilityLevels,
    CompatibilityNamespace, CompatibilityObservation, CompatibilityOutput, CompatibilityReceipt,
    ContextBuildInput, ContextBuildOutput, ContextBuildServiceRequest, DIAGNOSTICS_TOOL_NAME,
    DiagnosticsInput, DiagnosticsOutput, DiagnosticsServiceRequest,
    GET_ARCHITECTURE_ALIAS_TOOL_NAME, GET_CODE_SNIPPET_ALIAS_TOOL_NAME,
    GET_GRAPH_SCHEMA_ALIAS_TOOL_NAME, GRAPH_ARCHITECTURE_TOOL_NAME, GRAPH_EVIDENCE_TOOL_NAME,
    GRAPH_SEARCH_TOOL_NAME, GRAPH_STATUS_TOOL_NAME, GRAPH_TRACE_TOOL_NAME, GetArchitectureInput,
    GetCodeSnippetInput, GetGraphSchemaInput, GraphArchitectureInput, GraphArchitectureOutput,
    GraphEvidenceInput, GraphEvidenceOutput, GraphImpactInput, GraphImpactOutput,
    GraphReadServiceOutput, GraphReadServiceRequest, GraphSearchInput, GraphSearchOutput,
    GraphStatusInput, GraphStatusOutput, GraphTraceInput, GraphTraceOutput,
    HISTORICAL_MEMORY_SCHEMA_VERSION, HISTORICAL_MEMORY_TOOL_NAME, HistoricalMemoryApplicability,
    HistoricalMemoryCoverage, HistoricalMemoryEvidence, HistoricalMemoryEvidenceBasis,
    HistoricalMemoryInput, HistoricalMemoryOutput, HistoricalMemoryServiceRequest,
    HistoricalMemoryTarget, HistoricalMemoryTargetKind, IMPACT_ANALYZE_TOOL_NAME,
    INCUMBENT_COMPATIBLE_PROFILE, INCUMBENT_COMPATIBLE_SURFACE, INDEX_STATUS_ALIAS_TOOL_NAME,
    IndexStatusInput, MAX_MCP_INTEROPERABLE_INTEGER, MEMORY_MANAGE_SCHEMA_VERSION,
    MEMORY_MANAGE_TOOL_NAME, MEMORY_RECALL_TOOL_NAME, McpArchitectureMapFile,
    McpArchitectureMapLanguage, McpArchitectureOverviewKind, McpArchitectureOverviewRoot,
    McpConfigurationIdentity, McpContextCoverage, McpContextItem, McpContextMemoryItem,
    McpContextMemoryProjection, McpContextOmission, McpContextSourceItem, McpCoverage,
    McpDiagnosticsMemoryProjection, McpGraphArchitectureCount, McpGraphCandidate,
    McpGraphCardinality, McpGraphContext, McpGraphDefinition, McpGraphEdge, McpGraphEvidence,
    McpGraphImpact, McpGraphPublication, McpGraphSite, McpGraphTrace, McpGraphTraceCoverage,
    McpGraphTraceTruncation, McpMemoryCandidate, McpMemoryCoverage, McpMemoryEvidence,
    McpMemoryOccurrence, McpMemoryProducer, McpMemoryRecord, McpMemoryTarget,
    McpOutboundSitesDeclaration, McpOutboundSyntaxSite, McpPhase2ContextAttribution,
    McpPhase2ContextItem, McpPhase2ContextOmission, McpPhase2ContextPayload,
    McpPhase2ContextProviderCoverage, McpPhase2ContextScope, McpRelevantPath,
    McpRepositoryTopologyCategory, McpRepositoryTopologyCoverage, McpRepositoryTopologyEntry,
    McpScipOccurrence, McpScipOverlay, McpScipRelationship, McpScipRelationshipTraceEdge,
    McpScipRelationshipTraceOverlay, McpSearchMatch, McpSelectedMemory, McpSpan, McpSymbol,
    McpTestMarkerLanguageCoverage, MemoryManageDatabaseIdentityStatus,
    MemoryManageFileIdentityStatus, MemoryManageInput, MemoryManageMaintenanceStatus,
    MemoryManageMaintenanceStepStatus, MemoryManageOperation, MemoryManageOutput,
    MemoryManagePublicationStatus, MemoryManagePublicationStepStatus, MemoryManageReceipt,
    MemoryManageReviewDecision, MemoryManageServiceRequest, MemoryMutationOperation,
    MemoryMutationRequestScope, MemoryRecallInput, MemoryRecallOutput, MemoryRecallServiceRequest,
    MemoryRecallServiceSelection, NativeTaskState, NativeTaskStatus, OUTBOUND_SITES_TOOL_NAME,
    OutboundSitesInput, OutboundSitesOutput, OutboundSitesSelectorOutput,
    OutboundSitesServiceRequest, PERSONAL_MEMORY_SCHEMA_VERSION, PERSONAL_MEMORY_TOOL_NAME,
    PHASE2_CONTEXT_BUILD_TOOL_NAME, PersonalMemoryInput, PersonalMemoryKind,
    PersonalMemoryLifecycle, PersonalMemoryOperation, PersonalMemoryOutput,
    PersonalMemoryRecordOutput, PersonalMemoryServiceRequest, Phase2ContextBuildInput,
    Phase2ContextBuildOutput, Phase2ContextBuildServiceRequest, RELEVANT_PATHS_TOOL_NAME,
    REPOSITORY_TOPOLOGY_TOOL_NAME, RelevantPathsInput, RelevantPathsOutput,
    RelevantPathsServiceRequest, RepositoryService, RepositoryServiceError,
    RepositoryTopologyInput, RepositoryTopologyOutput, RepositoryTopologyServiceRequest,
    SCIP_EVIDENCE_TOOL_NAME, SCIP_RELATIONSHIP_TRACE_TOOL_NAME, SCIP_SYMBOL_RESOLVE_TOOL_NAME,
    SEARCH_CODE_ALIAS_TOOL_NAME, SEARCH_GRAPH_ALIAS_TOOL_NAME, SYMBOL_GET_TOOL_NAME,
    SYMBOL_SEARCH_TOOL_NAME, SYNTAX_SITE_SEARCH_TOOL_NAME, ScipEvidenceInput, ScipEvidenceOutput,
    ScipEvidenceServiceRequest, ScipRelationshipTraceInput, ScipRelationshipTraceOutput,
    ScipRelationshipTraceServiceRequest, ScipSymbolResolveInput, ScipSymbolResolveOutput,
    ScipSymbolResolveServiceRequest, SearchCodeInput, SearchGraphInput, SymbolGetInput,
    SymbolGetOutput, SymbolGetServiceRequest, SymbolSearchInput, SymbolSearchOutput,
    SymbolSearchServiceRequest, SymbolSelectorOutput, SyntaxSiteSearchInput,
    SyntaxSiteSearchOutput, SyntaxSiteSearchServiceRequest, TRACE_PATH_ALIAS_TOOL_NAME,
    TestMarkersInput, TestMarkersOutput, TestMarkersServiceRequest, TracePathInput,
};
