//! Bounded local MCP transport and versioned wire DTOs.

mod server;
mod transport;
mod wire;

pub use server::{
    DEFAULT_MCP_OPERATION_CONCURRENCY, MAX_MCP_REGISTERED_REPOSITORIES, McpRepositoryRegistryError,
    McpServeError, RepoWitnessMcpServer, serve_stdio, serve_stdio_with_memory_writes,
    serve_stdio_with_repository_catalog,
};
pub use transport::{BoundedLineReader, BoundedLineReaderLimitError, MAX_MCP_INPUT_LINE_BYTES};
pub use wire::{
    ARCHITECTURE_MAP_TOOL_NAME, ARCHITECTURE_OVERVIEW_LIMITATIONS, ARCHITECTURE_OVERVIEW_TOOL_NAME,
    ArchitectureMapInput, ArchitectureMapOutput, ArchitectureMapServiceRequest,
    ArchitectureOverviewInput, ArchitectureOverviewOutput, ArchitectureOverviewServiceRequest,
    CHANGE_REVIEW_SCHEMA_VERSION, CHANGE_REVIEW_TOOL_NAME, CODE_GRAPH_QUERY_PROFILE_VERSION,
    CODE_GRAPH_QUERY_SCHEMA_VERSION, CODE_GRAPH_QUERY_TOOL_NAME, CODE_SEARCH_TOOL_NAME,
    CONTEXT_BUILD_TOOL_NAME, CROSS_REPOSITORY_SEARCH_TOOL_NAME, ChangeReviewInput,
    ChangeReviewOutput, ChangeReviewServiceRequest, CodeGraphQueryInput, CodeGraphQueryOutput,
    CodeGraphQueryResultOutput, CodeGraphQueryServiceRequest, CodeSearchInput, CodeSearchOutput,
    CodeSearchServiceRequest, CrossRepositorySearchInput, CrossRepositorySearchOutput,
    CrossRepositorySearchRepository, CrossRepositorySearchServiceRequest, DIAGNOSTICS_TOOL_NAME,
    DiagnosticsInput, DiagnosticsOutput, DiagnosticsServiceRequest, EvidenceContextBuildInput,
    EvidenceContextBuildOutput, EvidenceContextBuildServiceRequest, GRAPH_ARCHITECTURE_TOOL_NAME,
    GRAPH_EVIDENCE_TOOL_NAME, GRAPH_SEARCH_TOOL_NAME, GRAPH_STATUS_TOOL_NAME,
    GRAPH_TRACE_TOOL_NAME, GraphArchitectureInput, GraphArchitectureOutput, GraphEvidenceInput,
    GraphEvidenceOutput, GraphImpactInput, GraphImpactOutput, GraphReadServiceOutput,
    GraphReadServiceRequest, GraphSearchInput, GraphSearchOutput, GraphStatusInput,
    GraphStatusOutput, GraphTraceInput, GraphTraceOutput, IMPACT_ANALYZE_TOOL_NAME,
    MAX_CROSS_REPOSITORY_RESULTS, MAX_CROSS_REPOSITORY_SELECTIONS, MAX_MCP_INTEROPERABLE_INTEGER,
    MEMORY_MANAGE_SCHEMA_VERSION, MEMORY_MANAGE_TOOL_NAME, MEMORY_RECALL_TOOL_NAME,
    McpArchitectureMapFile, McpArchitectureMapLanguage, McpArchitectureOverviewKind,
    McpArchitectureOverviewRoot, McpChangeReviewPath, McpConfigurationIdentity, McpCoverage,
    McpDiagnosticsMemoryProjection, McpEvidenceContextAttribution, McpEvidenceContextItem,
    McpEvidenceContextOmission, McpEvidenceContextPayload, McpEvidenceContextProviderCoverage,
    McpEvidenceContextScope, McpGraphArchitectureCount, McpGraphCandidate, McpGraphCardinality,
    McpGraphContext, McpGraphDefinition, McpGraphEdge, McpGraphEvidence, McpGraphImpact,
    McpGraphPublication, McpGraphSite, McpGraphTrace, McpGraphTraceCoverage,
    McpGraphTraceTruncation, McpMemoryCandidate, McpMemoryCoverage, McpMemoryEvidence,
    McpMemoryOccurrence, McpMemoryProducer, McpMemoryRecord, McpMemoryTarget,
    McpOutboundSitesDeclaration, McpOutboundSyntaxSite, McpRelevantPath,
    McpRepositoryTopologyCategory, McpRepositoryTopologyCoverage, McpRepositoryTopologyEntry,
    McpSearchMatch, McpSelectedMemory, McpSpan, McpSymbol, McpTestMarkerLanguageCoverage,
    MemoryManageDatabaseIdentityStatus, MemoryManageFileIdentityStatus, MemoryManageInput,
    MemoryManageMaintenanceStatus, MemoryManageMaintenanceStepStatus, MemoryManageOperation,
    MemoryManageOutput, MemoryManagePublicationStatus, MemoryManagePublicationStepStatus,
    MemoryManageReceipt, MemoryManageReviewDecision, MemoryManageServiceRequest,
    MemoryMutationOperation, MemoryMutationRequestScope, MemoryRecallInput, MemoryRecallOutput,
    MemoryRecallServiceRequest, MemoryRecallServiceSelection, OUTBOUND_SITES_TOOL_NAME,
    OutboundSitesInput, OutboundSitesOutput, OutboundSitesSelectorOutput,
    OutboundSitesServiceRequest, RELEVANT_PATHS_TOOL_NAME, REPOSITORY_TOPOLOGY_TOOL_NAME,
    RelevantPathsInput, RelevantPathsOutput, RelevantPathsServiceRequest, RepositoryService,
    RepositoryServiceError, RepositoryTopologyInput, RepositoryTopologyOutput,
    RepositoryTopologyServiceRequest, SYMBOL_GET_TOOL_NAME, SYMBOL_SEARCH_TOOL_NAME,
    SYNTAX_SITE_SEARCH_TOOL_NAME, SymbolGetInput, SymbolGetOutput, SymbolGetServiceRequest,
    SymbolSearchInput, SymbolSearchOutput, SymbolSearchServiceRequest, SymbolSelectorOutput,
    SyntaxSiteSearchInput, SyntaxSiteSearchOutput, SyntaxSiteSearchServiceRequest,
    TestMarkersInput, TestMarkersOutput, TestMarkersServiceRequest,
};
